language: objective-c
xcode_project: CoreDataStack.xcodeproj
xcode_scheme: CoreDataStack
xcode_sdk: iphonesimulator
osx_image: xcode7
before_install: brew uninstall xctool && brew install --HEAD xctool
